<?php

declare(strict_types=1);

/**
 * @file
 * Provides an offices entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\user\UserInterface;
use Drupal\views\Entity\View;

/**
 * Implements hook_theme().
 */
function offices_theme(): array {
  return [
    'officeBlock' => [
      'variables' => [
        'content' => NULL,
        'countries' => NULL,
      ],
      
      'template' => 'offices',
    ],
    
  ];
}

/**
 * Prepares variables for offices templates.
 *
 * Default template: offices.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the offices information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_offices(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function offices_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish officess.
      $storage = \Drupal::entityTypeManager()->getStorage('offices');
      $offices_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($offices_ids) as $offices) {
        $offices->set('status', FALSE)->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize officess.
      $storage = \Drupal::entityTypeManager()->getStorage('offices');
      $offices_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($offices_ids) as $offices) {
        $offices->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function offices_user_predelete(UserInterface $account): void {
  // Delete officess that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('offices');
  $offices_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($offices_ids)
  );
}
